# Generated by Django 4.0 on 2022-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('runtime', models.FloatField()),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
