# Generated by Django 4.0 on 2022-02-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='movie_release_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie_title',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(),
        ),
    ]
